baseURL: "https://ashutosh1206.github.io/"
languageCode: "en-us"
title: "Ash's blog"
theme: "PaperMod"
paginate: 5

params:
  env: production

  # OpenGraph and Twitter tags
  # og:title
  title: Ash's blog
  # og:description
  description: Security Software Engineer

  defaultTheme: auto
  label:
    text: "Home"
    # icon:
    # iconHeight: 35

  profileMode:
    enabled: true
    title: "Ashutosh Ahelleya"
    subtitle: "Security Software Engineer at a startup. Infosec masters student at <strong>[UCL](https://ucl.ac.uk/)</strong>"
    imageUrl: "/avatar.jpeg"
    imageTitle: "henlo"
    imageWidth: 200
    imageHeight: 200

  socialIcons:
    - name: email
      url: "mailto:ashutosh.ahelleya@gmail.com"
    - name: linkedin
      url: "https://linkedin.com/in/ashutosh1206"
    - name: github
      url: "https://github.com/ashutosh1206"
    - name: twitter
      url: "https://twitter.com/ashutosha_"
    - name: mastodon
      url: "https://infosec.exchange/@ashutosh"
    - name: goodreads
      url: "https://www.goodreads.com/user/show/100766792-ashutosh-ahelleya"

menu:
  main:
    - name: About
      url: about/
    - name: Blog
      url: blog/
      weight: 5
    - name: Archive
      url: archive/
    - name: CTF
      url: ctf/
